### PR TITLE
Add script to generate list of supported coins

### LINKED ISSUE #68: Add table of supported icons on project README
Hey,

I think it would be nice if this project had a complete list of supported icons (including coin name / image name). A couple of times I wanted to search for an icon and I had to look through all images, and see if some of them had a different naming convention.

I can create a PR if you are OK with this

### PR DESCRIPTION
**Pull request by aviggiano**
Create node script to generate table of supported coins.

The script searches the `svg` directory in search for coin names and compare them with CoinMarketCap names. If a coin symbol is different, the name defaults to `?`. Then, it creates a markdown table and updates the `README.md` file.
The script also works independently for `black`, `color`, `icon`, `white` icons (although it seems that they are always present, so this feature might be removed if it is not necessary).

```
npm run table
```

Fix #68

### CODE REVIEW

**Comment by cjdowner** [comment]
Thanks for the contribution!

Little bit out of my depth here with this. OK, so I need to run that command, and the readme updates? I think a separate file might be best, and I'm not sure it needs to be a table, because all variants are always included.

Thinking how this could be paired with the manifest, so it can play nicely with #73. The manifest is something that I update by hand, but that's because I'm a designer, not a developer haha.

**Comment by aviggiano** [comment]
Hey,

I wrote the script using Node.js since you were already using npm, so I thought it might be easier to maintain it. 

However, now looking at that site, I think that it doesn't make sense to create a script to generate a table, since 

1. it is always necessary to manually create a new icon for new coins, so it is not a big deal to manually update a manifest file too
2. people can see the icons and search for specific coins on the website.

I will update this PR so that it works with #73

**Comment by aviggiano** [comment]
By the way, do you mind going through [this process](https://pages.github.com/) to create a github page under your username? 

That's important because the page created by the contributor who did #73 is not automatically updated when you add new coins. 

Also, I believe the project README could mention project website.

**Comment by aviggiano** [comment]
Hey again,

I just noticed that the PR #73 was very recently opened, so that's why the project page is not on the README :laughing: 

Anyway, I will update this PR so that the manifest file is automatically populated with the coin names when the user opens the project website, so it will not be necessary to run any script at all.

**Comment by aviggiano** [comment]
Done @cjdowner

**Comment by cjdowner** [comment]
@aviggiano Great, thanks for helping out. I've got GH pages set up and the project has a URL - http://cryptoicons.co

Will merge this in and add the new URL to the readme when I commit with the newest icons tonight. 👍

**Pull request merged**
