### PR TITLE
Add Denarius (DNR) Icons

### PR DESCRIPTION
**Pull request by carsenk**
Added the Denarius (DNR) Icons, please let me know if you need anything else!

### CODE REVIEW

**Comment by carsenk** [comment]
Can you please merge this in @cjdowner ?

**Comment by carsenk** [comment]
@cjdowner It would be nice to get this merged in since we are trying to utilize the icons within the HyperDEX project

**Comment by cjdowner** [comment]
Sorry - I have been offline. Merging.

**Comment by sindresorhus** [comment]
The SVGs in this PR are not correct. They are just an SVG wrapping a bitmap image encoded as an inline data URI. Each DNR SVG file takes up 7.8 MB. I would suggest reverting this PR until that's fixed.

The PNGs should also be run through Imageoptim to reduce their size.

**Comment by sindresorhus** [comment]
@carsenk I removed your commit as it significantly increased the repo size. Can you submit a new PR with fixed SVG images?

**Comment by sindresorhus** [comment]
@carsenk If you can send me the vector version of the logo, I'll add it for you.

**Comment by carsenk** [comment]
@sindresorhus There is a new PR up with the new SVGs: https://github.com/hyperdexapp/cryptocurrency-icons/pull/139

**Pull request merged**
